export const OPENXIANGDA_MODULE_OPTIONS = Symbol(
  'OPENXIANGDA_MODULE_OPTIONS'
);

export const OPENXIANGDA_REQUIRED_CAPABILITY = Symbol(
  'OPENXIANGDA_REQUIRED_CAPABILITY'
);

export const OPENXIANGDA_OPERATION_CONTRACT = Symbol(
  'OPENXIANGDA_OPERATION_CONTRACT'
);

export const OPENXIANGDA_EVENT_RECEIPT_STORE = Symbol(
  'OPENXIANGDA_EVENT_RECEIPT_STORE'
);
