export {
  defineOpenXiangdaApp,
  defineApplicationModule,
  // 模块化迁移（如 GAP-MODULE-001/002 的验收脚本）需要直接投影模块声明；
  // 与声明 API 同源再导出，应用不再引用 dist 文件路径。
  materializeApplicationModules,
  defineDataModel,
  defineResourceForm,
  defineResourceList,
  defineAdminNavigation,
  adminNavigationGroup,
  adminResourcePage,
  adminOperationPage,
  adminApplicationTodoCenterPage,
  renderAdminNavigationSuggestion,
  suggestAdminNavigation,
  composeAppOperationSchemas,
  composeJsonSchema,
  currentUserDataPolicy,
  dataPolicyExpression,
  resourceRecordSchema,
  resourceReadPolicy,
  resourceCapabilityCodes,
  resourceRoleCapabilities,
  schemaRef,
  type AppDataFieldAccessDeclaration,
  type AppDataFieldDeclaration,
  type AppDataResourceDeclaration,
  type AppDataModelDeclaration,
  type AppModelFieldDeclaration,
  type AppModuleDeclaration,
  type AppCrudViewDeclaration,
  type AppResourceFormDeclaration,
  type AppResourceListDeclaration,
  type AdminNavigationSuggestionSource,
  type WorkflowDefinitionDeclaration,
  type OpenXiangdaAppConfig,
  type OpenXiangdaAppDeclaration,
  type AppOperationSchemasInput,
  type JsonSchemaDefinitions,
  type ResourceRecordSchemaOptions,
} from 'openxiangda-devkit-core';
