/**
 * Application-facing NestJS surface for OpenXiangda 2.0.
 *
 * Applications receive only current-user-union, Perspective read projection,
 * application-principal, Data API, runtime, event and bounded operation APIs.
 */
export {
  bootstrapOpenXiangdaApplication,
  OpenXiangdaModule,
  OpenXiangdaAuthzGuard,
  RequireCapability,
  OpenXiangdaOperation,
  CurrentPrincipal,
  CurrentUser,
  CurrentPerspective,
  currentUserFromVerifiedContext,
  currentUserFromPrincipal,
  CurrentApplicationPrincipal,
  OpenXiangdaDataApiService,
  OpenXiangdaBusinessDataApiService,
  OpenXiangdaBusinessDirectoryService,
  OpenXiangdaBusinessProcessService,
  OpenXiangdaWorkflowService,
  WorkflowAssigneeProvider,
  OpenXiangdaBusinessNotificationService,
  OpenXiangdaNotificationService,
  OpenXiangdaTodoService,
  OpenXiangdaLoggerService,
  OpenXiangdaPlatformError,
  OpenXiangdaApplicationDataApiService,
  OpenXiangdaApplicationCredentials,
  OpenXiangdaRuntimeLeaseService,
  OpenXiangdaRuntimeSecrets,
  OpenXiangdaStandardOperations,
  OpenXiangdaEventContext,
  OpenXiangdaEventHandler,
  OpenXiangdaEventRegistry,
  OpenXiangdaEventRetryableError,
  OpenXiangdaEventDeterministicError,
  eventSigningSecretsFromEnvironment,
  assertValidTimeInterval,
  databaseNowAssertion,
  idempotentTransaction,
} from 'openxiangda-nest';

export type {
  OpenXiangdaApplicationBootstrapOptions,
  OpenXiangdaModuleOptions,
  OpenXiangdaApplicationModuleOptions,
  OpenXiangdaOAuthClientOptions,
  OpenXiangdaFetch,
  OpenXiangdaLogFields,
  OpenXiangdaPlatformRequestDiagnostic,
  OpenXiangdaCurrentUser,
  OpenXiangdaServicePrincipal,
  OpenXiangdaConnectedDevelopmentStatus,
  OpenXiangdaDomainEventEmitInput,
  OpenXiangdaDomainEventEmitResult,
  OpenXiangdaBusinessActionContext,
  OpenXiangdaBusinessNotificationInput,
  OpenXiangdaBusinessProcessCommitInput,
  WorkflowAssigneeProviderHandler,
  OpenXiangdaEventBusinessNotificationInput,
  OpenXiangdaRuntimeLeaseState,
  OpenXiangdaEventHandlerContext,
  OpenXiangdaEventHandlerDeclaration,
  OpenXiangdaEventConsumer,
  TimeInterval,
  MeetingReservationOperationInput,
  CourseSelectionOperationInput,
  VisitorReservationOperationInput,
} from 'openxiangda-nest';

export {
  OPENXIANGDA_NOTIFICATION_BUSINESS_SEND_V2,
  OPENXIANGDA_NOTIFICATION_EVENT_SEND_V2,
} from 'openxiangda-contracts';
